menu:
  - name: Blog
    path: /
    icon: fa fa-home
  - name: Archive
    path: /archives/
    icon: fa fa-folder-open-o
  - name: JianShu
    path: https://www.jianshu.com/u/b0702a59ee51
    icon: fa fa-weibo
  - name: GitHub
    path: https://github.com/RaymondXiao1991
    icon: fa fa-github-alt
  - name: CNBlogs
    path: http://www.cnblogs.com/xiaoqingyang/
    icon: iconfont coding
  - name: About
    path: /about/
    icon: fa fa-info-circle

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
