menu:
  - name: Blog
    path: /
    icon: fa fa-home
  - name: Archive
    path: /archives/
    icon: fa fa-folder-open-o
  - name: Weibo
    path: http://weibo.com/fengxianhe
    icon: fa fa-weibo
  - name: GitHub
    path: https://github.com/hefengxian
    icon: fa fa-github-alt
  - name: Coding
    path: https://coding.net/u/hfx
    icon: iconfont coding
  - name: About
    path: /about/
    icon: fa fa-info-circle

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
